// Generated by CoffeeScript 1.4.0

/*                                                                                                                                                                                                                 
 * Copyright 2011 Dustin Frisch<fooker@lab.sh>
 * 
 * This file is part of box.
 * 
 * box is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * box is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with box. If not, see <http://www.gnu.org/licenses/>.
*/


(function() {
  var Model;

  Model = (function() {

    function Model() {
      var parameters,
        _this = this;
      parameters = get_url_parameters();
      this.id = parameters['i'];
      this.file = parameters['f'];
      this.size = ko.observable('');
      this.type = ko.observable('');
      this.loading = ko.observable(true);
      this.download_url = "" + base_url + "/storage/" + this.id + "?f=" + this.file;
      $.ajax({
        'url': "" + base_url + "/storage/" + this.id,
        'type': 'HEAD',
        'processData': false,
        'success': function(data, textStatus, jqXHR) {
          _this.size(parseInt(jqXHR.getResponseHeader('Content-Length')));
          _this.type(jqXHR.getResponseHeader('Content-Type'));
          return console.log(jqXHR.getAllResponseHeaders());
        },
        'complete': function() {
          return _this.loading(false);
        }
      });
    }

    return Model;

  })();

  ko.applyBindings(new Model());

}).call(this);
